name: Update Website on Desktop Release

on:
  repository_dispatch:
    types: [desktop-release]

jobs:
  update-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Update releases data
        run: |
          curl -s https://api.github.com/repos/asgardex/asgardex-desktop/releases | jq '.[0:10]' > src/releases.json
          
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add src/releases.json
          git commit -m "Update releases from asgardex-desktop"
          git push origin master